name: flutter_csv_import
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
#  csv: ^4.1.0
  filepicker_windows: ^1.0.0
  font_awesome_flutter: ^8.10.0
  path_provider: ^1.6.27
  getwidget: ^1.2.4
  get: ^3.24.0
  http: ^0.12.2
  grizzly_io: ^2.2.2
  csv_reader: ^1.0.2
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

